/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Componente01Msmolina5 {
        "apiUrl": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLComponente01Msmolina5Element extends Components.Componente01Msmolina5, HTMLStencilElement {
    }
    var HTMLComponente01Msmolina5Element: {
        prototype: HTMLComponente01Msmolina5Element;
        new (): HTMLComponente01Msmolina5Element;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "componente-01-msmolina5": HTMLComponente01Msmolina5Element;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface Componente01Msmolina5 {
        "apiUrl"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "componente-01-msmolina5": Componente01Msmolina5;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "componente-01-msmolina5": LocalJSX.Componente01Msmolina5 & JSXBase.HTMLAttributes<HTMLComponente01Msmolina5Element>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
